---
description: "sensu-ruby32-runtime"
builds:
- platform: "debian11"
  arch: "amd64"
  asset_filename: "sensu-ruby-runtime_#{version}_ruby-3.2.2_debian11_linux_amd64.tar.gz"
  sha_filename: "sensu-ruby-runtime_#{version}_sha512-checksums.txt"
  filter:
  -  "entity.system.os == 'linux'"
  -  "entity.system.arch == 'amd64'"
  -  "entity.system.platform_family == 'debian'"
  -  "entity.system.platform_version.split('.')[0] == '11'"
- platform: "debian10"
  arch: "amd64"
  asset_filename: "sensu-ruby-runtime_#{version}_ruby-3.2.2_debian10_linux_amd64.tar.gz"
  sha_filename: "sensu-ruby-runtime_#{version}_sha512-checksums.txt"
  filter:
  -  "entity.system.os == 'linux'"
  -  "entity.system.arch == 'amd64'"
  -  "entity.system.platform_family == 'debian'"
  -  "entity.system.platform_version.split('.')[0] == '10'"
- platform: "debian"
  arch: "amd64"
  asset_filename: "sensu-ruby-runtime_#{version}_ruby-3.2.2_debian_linux_amd64.tar.gz"
  sha_filename: "sensu-ruby-runtime_#{version}_sha512-checksums.txt"
  filter:
  -  "entity.system.os == 'linux'"
  -  "entity.system.arch == 'amd64'"
  -  "entity.system.platform_family == 'debian'"
